CREATE TABLE `dt_student` (
 `student_id` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
 `personal_data_id` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
 `program_id` int(11) DEFAULT NULL,
 `study_program_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
 `academic_year_id` char(4) COLLATE utf8_unicode_ci NOT NULL,
 `finance_year_id` char(4) COLLATE utf8_unicode_ci NOT NULL,
 `student_number` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
 `student_date_enrollment` datetime DEFAULT NULL,
 `student_type` enum('regular','transfer') COLLATE utf8_unicode_ci DEFAULT NULL,
 `student_email` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
 `student_un_status` enum('yes','no') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'yes',
 `student_status` enum('candidate','participant','pending','active','inactive','dropout','resign') COLLATE utf8_unicode_ci DEFAULT 'candidate',
 `portal_sync` enum('0','1') COLLATE utf8_unicode_ci NOT NULL DEFAULT '1' COMMENT '0=sudah sync',
 `date_added` datetime NOT NULL,
 `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`student_id`),
 KEY `study_program_id` (`study_program_id`),
 KEY `dt_student_ibfk_2` (`personal_data_id`),
 KEY `academic_year_id` (`academic_year_id`),
 KEY `program_id` (`program_id`),
 KEY `finance_year_id` (`finance_year_id`),
 CONSTRAINT `dt_student_ibfk_1` FOREIGN KEY (`study_program_id`) REFERENCES `ref_study_program` (`study_program_id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `dt_student_ibfk_2` FOREIGN KEY (`personal_data_id`) REFERENCES `dt_personal_data` (`personal_data_id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `dt_student_ibfk_3` FOREIGN KEY (`academic_year_id`) REFERENCES `dt_academic_year` (`academic_year_id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `dt_student_ibfk_4` FOREIGN KEY (`program_id`) REFERENCES `ref_program` (`program_id`) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT `dt_student_ibfk_5` FOREIGN KEY (`finance_year_id`) REFERENCES `dt_academic_year` (`academic_year_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci