<div class="card">
    <div class="card-header">
        Generated Number
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="table_list" class="table table-bordered table-hover table-striped">
                <thead class="bg-dark">
                    <tr>
                        <th>Number</th>
                        <th>Letter Type</th>
                        <th>Generated By</th>
                        <th>To</th>
                        <th>Description</th>
                        <th>Letter Date</th>
                        <th>Generated Datetime</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<div class="modal" tabindex="-1" role="dialog" id="update_desc_letter_modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Update Description</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <input type="hidden" name="letter_number_id_description_update" id="letter_number_id_description_update">
                <textarea name="description_letter_update" id="description_letter_update" class="form-control"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btn_submit_description">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal" tabindex="-1" role="dialog" id="update_desc_letter_modal_17">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Update Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form onsubmit="return false" id="form_up17">
                    <input type="hidden" name="letter_number_id_description_update" id="letter_number_id_description_update_17">
                    <div class="row">
                        <div class="col-md-12 mb-2">
                            <textarea name="description_letter_update" id="description_letter_update_17" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <span><i>assigns to:</i></span>
                            <div class="btn-group btn-group-sm btn-group-toggle ml-4" data-toggle="buttons">
                                <label class="btn btn-primary btn-sm active">
                                    <input type="radio" name="letter_assigns_to_17" id="letter_assigns_to_lecturer_up17" autocomplete="off" value="lecturer"> Lecturer
                                </label>
                                <label class="btn btn-primary btn-sm">
                                    <input type="radio" name="letter_assigns_to_17" id="letter_assigns_student_up17" autocomplete="off" value="student"> Student
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div id="option_lecturer_up17" class="form-group">
                                <label for="employee_add_community">Lecturer</label>
                                <div class="input-group input-group-sm">
                                    <select name="employee_add_community" id="employee_add_community_up17" class="form-control" style="width: 80%">
                                        <option value=""></option>
                                    </select>
                                    <button class="btn btn-success btn-sm w-10" id="btn_add_lecturer_community_up17" type="button"><i class="fas fa-plus"></i> Add</button>
                                </div>
                            </div>
                            <div id="option_student_up17" class="form-group d-none">
                                <label for="student_id_add_community">Student</label>
                                <div class="input-group input-group-sm">
                                    <select name="student_id_add_community" id="student_id_add_community_up17" class="form-control" style="width: 80%">
                                        <option value=""></option>
                                    </select>
                                    <button class="btn btn-success btn-sm w-10" id="btn_add_student_community_up17" type="button"><i class="fas fa-plus"></i> Add</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table id="tablemember_community_up17" class="table table-bordered table-hovered">
                                    <thead class="bg-dark">
                                        <tr>
                                            <th>Name</th>
                                            <th>Position</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btn_submit_description_up17">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>
var tablemember_community_up17 = $('#tablemember_community_up17').DataTable({
    searching: false,
    info: false,
    paging: false,
    ordering: false
});

var table_list = $('table#table_list').DataTable({
    order: [[5, 'desc']],
    ajax: {
        url: '<?= base_url()?>apps/letter_numbering/get_list_number_generated',
        type: 'POST',
        // data: filter_data
    },
    columns: [
        {
            data: 'letter_number_result',
            render: function(data, type, row) {
                var html = (row.template_generated == '') ? data : row.template_generated;
                // return '<a id="show_result_number" href="javascript:void(0)">' + data + '</a>';
                return html;
            }
        },
        {data: 'letter_name'},
        {data: 'personal_data_name'},
        {data: 'letter_purpose'},
        {data: 'letter_description'},
        {data: 'letter_date'},
        {data: 'last_generate'},
        {
            data: 'letter_number_result',
            // visible : false,
            render: function(data, type, row) {
                html = '';
                if ('<?=$this->session->userdata("user");?>' == row.personal_data_id) {
                    html += '<div class="btn-group btn-group-sm" role="group" aria-label="action-group">';
                    var btn_update_letter = '<button type="button" id="btn_update_desc_letter" data-key="' + row.template_id + '" class="btn btn-info"><i class="fas fa-edit"></i></button>';

                    html += btn_update_letter;
                    html += '</div>';
                }
                return html;
            }
        },
    ],
});

$(function() {

    $('table#table_list tbody').on('click', 'button#btn_update_desc_letter', function(e) {
        e.preventDefault();
        var data_list = table_list.row($(this).parents('tr')).data();
        var template_id = data_list.template_id;

        $('textarea[name=description_letter_update]').val(decodeHTMLEntities(data_list.letter_description));
        $('input[name=letter_number_id_description_update]').val(data_list.letter_number_id);

        if (template_id == '17') {
            $('#update_desc_letter_modal_17').modal('show');
        }
        else {
            $('#update_desc_letter_modal').modal('show');
        }
    });

    $('button#btn_submit_description').on('click', function(e) {
        e.preventDefault();
        $.blockUI({baseZ: 2000});

        var description = decodeHTMLEntities($('#description_letter_update').val());
        var data = {
            desc: description,
            letter_number_id: $('#letter_number_id_description_update').val()
        }

        $.post('<?=base_url()?>apps/letter_numbering/update_description', data, function(result) {
            $.unblockUI();
            if (result.code == 0) {
                toastr.success('Success!');
                $('#update_desc_letter_modal').modal('hide');
                $('#description_letter_update').val('');
                table_list.ajax.reload(null, true);
            }
            else {
                toastr.warning(result.message, 'Warning!');
            }
        }, 'json').fail(function(params) {
            $.unblockUI();
            toastr.error('Error processing data!');
        })
    });

    $('button#btn_submit_description_up17').on('click', function(e) {
        e.preventDefault();
        $.blockUI({baseZ: 2000});

        var description = decodeHTMLEntities($('#description_letter_update').val());
        var data = $('#form_up17').serialize();
        data += '&template_id=17';

        $.post('<?=base_url()?>apps/letter_numbering/update_detailtemp_17', data, function(result) {
            $.unblockUI();
            if (result.code == 0) {
                toastr.success('Success!');
                $('#update_desc_letter_modal').modal('hide');
                $('#description_letter_update').val('');
                table_list.ajax.reload(null, true);
            }
            else {
                toastr.warning(result.message, 'Warning!');
            }
        }, 'json').fail(function(params) {
            $.unblockUI();
            toastr.error('Error processing data!');
        })
    });

    $('select#employee_add_community_up17').select2({
        allowClear: true,
        placeholder: "Please select..",
        minimumInputLength: 1,
        theme: "bootstrap",
        cache: false,
        ajax: {
            url: '<?=base_url()?>employee/get_lecturer_by_name',
            type: "POST",
            dataType: 'json',
            data: function (params) {
                return {
                    keyword: params.term
                }
            },
            processResults: function(result) {
                data = result.data;
                return {
                    results: $.map(data, function (item) {
                        return {
                            text: item.fullname,
                            id: item.personal_data_id,
                            employee_key: item.employee_id
                        }
                    })
                }
            }
        }
    });

    $('select#student_id_add_community_up17').select2({
        allowClear: true,
        placeholder: "Please select..",
        minimumInputLength: 1,
        theme: "bootstrap",
        cache: false,
        ajax: {
            url: '<?=base_url()?>student/get_student_by_name',
            type: "POST",
            dataType: 'json',
            data: function (params) {
                return {
                    keyword: params.term
                }
            },
            processResults: function(result) {
                data = result.data;
                return {
                    results: $.map(data, function (item) {
                        return {
                            text: item.personal_data_name + ' - ' + item.study_program_abbreviation + '/' + item.finance_year_id,
                            id: item.personal_data_id,
                            student_key: item.student_id
                        }
                    })
                }
            }
        }
    });

    $('input[name=letter_assigns_to_17]').on('change', function(e) {
        e.preventDefault();

        if ($(this).val() == 'student') {
            $('#option_student_up17').removeClass('d-none');
            $('#option_lecturer_up17').addClass('d-none');
        }
        else {
            $('#option_lecturer_up17').removeClass('d-none');
            $('#option_student_up17').addClass('d-none');
        }
    });

    $('#tablemember_community_up17 tbody').on('click', 'button#remove_row_table_17', function(e) {
        e.preventDefault();

        tablemember_community_up17.row($(this).parents('tr')).remove().draw();
    });

    $('button#btn_add_lecturer_community_up17').on('click', function(e) {
        e.preventDefault();

        var s_data = $('#employee_add_community_up17').select2('data');
        add_table_17(s_data[0].text, s_data[0].employee_key, 'employee')
    });
    
    $('button#btn_add_student_community_up17').on('click', function(e) {
        e.preventDefault();

        var s_data = $('#student_id_add_community_up17').select2('data');
        add_table_17(s_data[0].text, s_data[0].student_key, 'student')
    })
});

function decodeHTMLEntities(text) {
    return $("<textarea/>")
        .html(text)
        .text();
}

function add_table_17(nametext, id, type) {
    let btn_remove = '<button name="remove_row_table" id="remove_row_table_17" type="button" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></button>';
    var nameid = (type == 'student') ? 'student_id[]' : 'employee_id[]';
    let namecolumn = nametext + ' <input type="hidden" name="' + nameid + '" value="' + id + '">';
    var rowNode = tablemember_community_up17.row.add( [ namecolumn, type.toUpperCase(), btn_remove ] )
        .draw()
        .node();

    $( rowNode )
        .css( 'color', 'red' )
        .animate( { color: 'black' } );
}
</script>